sources:
  - name: raw
    database: user_db_gecko
    schema: raw
    tables:
      - name: user_session_channel
        identifier: user_session_channel
      - name: session_timestamp
        identifier: session_timestamp